### ISSUE TITLE
[故障] 安装此插件后无法发送聊天消息

### ISSUE THREAD

**Issue by Mdxin** [Arasple/TrChat#19]
安装此插件后无法发送聊天消息。

```
[20:09:21 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v1.7-R2
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:d381e06]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:d381e06]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:d381e06]
        at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1506) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1440) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:41) ~[la.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at io.izzel.taboolib.module.locale.TLocale$Tellraw.send(TLocale.java:128) ~[?:?]
        at io.izzel.taboolib.module.tellraw.TellrawJson.send(TellrawJson.java:68) ~[?:?]
        at io.izzel.taboolib.module.tellraw.TellrawJson.send(TellrawJson.java:63) ~[?:?]
        at me.arasple.mc.trchat.chat.listeners.ListenerChatEvent.onChat(ListenerChatEvent.java:60) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor100.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:d381e06]
        ... 10 more
```

### 触发条件

1. 安装插件
1. 启动并登入服务器
1. 发送任何聊天消息，例如“a”
1. 游戏内无任何反应，后台输出错误如上所述

### 测试环境

服务端：Mohist-d381e06-server
服务端核心：minecraft_server.1.12.2

插件列表：

1. [前置]PlaceholderAPI-2.10.4
1. [权限]LuckPerms-Bukkit-4.4.1
1. [信息 管理]太弱聊天 TrChat-1.7-R2
1. [综合 管理]基础 EssentialsX-2.17.1.52
1. [综合 管理]基础 EssentialsXAntiBuild-2.17.1.52
1. [综合 管理]基础 EssentialsXProtect-2.17.1.52
1. [综合 管理]基础 EssentialsXSpawn-2.17.1.52

**Comment by Arasple** [comment]
Mohist 暂时不支持
