### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by EmptyIrony** [Arasple/TrChat#29]
version: PaperSpigot 1.8.8

dump:
 [TrChat] Enabling TrChat v1.7-R4
 java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/NonNullList
        at me.arasple.mc.trchat.nms.InternalPacketUtils.<clinit>(InternalPacketUtils.java:24)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at io.izzel.taboolib.module.inject.TInjectAsm.postLoad(TInjectAsm.java:25)
        at io.izzel.taboolib.TabooLibLoader.lambda$postLoadClass$4(TabooLibLoader.java:143)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.izzel.taboolib.TabooLibLoader.postLoadClass(TabooLibLoader.java:140)
        at io.izzel.taboolib.PluginLoader$1.onStarting(PluginLoader.java:51)
        at io.izzel.taboolib.PluginLoader.lambda$start$2(PluginLoader.java:121)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.izzel.taboolib.PluginLoader.start(PluginLoader.java:121)
        at me.arasple.mc.trchat.TrChatPlugin.onEnable(TrChatPlugin.java:451)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:363)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:322)
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406)
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370)
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:271)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:562)
        at java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.NonNullList
        at java.lang.ClassLoader.findClass(Unknown Source)
        at io.izzel.taboolib.common.plugin.bridge.BridgeLoader.findClass(BridgeLoader.java:36)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 26 more

**Comment by EmptyIrony** [comment]
The latest version fixed it
