### ISSUE TITLE
TrChat在Mohist端上的报错

### ISSUE THREAD

**Issue by Mr-Notch** [Arasple/TrChat#6]
服务端版本：Mohist-cf8635e-1.12.2
服务端构建站：[](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/)
TrChat为最新版
在玩家说话的时候发不出去消息，并且后台弹出如下报错：

`[19:04:32 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v1.5
 java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getHandle()Lnet/minecraft/server/v1_12_R1/EntityPlayer;
        at io.izzel.taboolib.module.packet.channel.InternalChannelExecutor.sendPacket(InternalChannelExecutor.java:18) ~[?:?]
        at io.izzel.taboolib.module.packet.TPacketHandler.sendPacket(TPacketHandler.java:48) ~[?:?]
        at io.izzel.taboolib.module.tellraw.internal.InternalTellraw.sendRawMessage(InternalTellraw.java:34) ~[?:?]
        at io.izzel.taboolib.module.locale.TLocale$Tellraw.send(TLocale.java:128) ~[?:?]
        at io.izzel.taboolib.module.tellraw.TellrawJson.send(TellrawJson.java:68) ~[?:?]
        at io.izzel.taboolib.module.tellraw.TellrawJson.send(TellrawJson.java:63) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_231]
        at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_231]
        at me.arasple.mc.trchat.listeners.ListenerAsyncChat.onChat(ListenerAsyncChat.java:55) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor691.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:c990fd7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:c990fd7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:c990fd7]
        at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1503) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1437) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:41) ~[la.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by Arasple** [comment]
暂时不支持 Mohist

**Comment by Mr-Notch** [comment]
Sure, 我已经在联系Mohist作者了..让其兼容Taboolib

发送自 Windows 10 版邮件应用

发件人: Arasple
发送时间: 2019年11月16日 19:46
收件人: Arasple/TrChat
抄送: Mr-Notch; Author
主题: Re: [Arasple/TrChat] TrChat在Mohist端上的报错 (#6)

Closed #6.
